/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bankapp;

import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ÖZGENUR YILDIZ
 */
public class frmParaYatir extends javax.swing.JFrame {
String ucret1;
 frmKullaniciEkran frm=new frmKullaniciEkran();
    /**
     * Creates new form frmParaYatir
     */
    public frmParaYatir() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlParaYAtir = new javax.swing.JPanel();
        lblBakiyeYazi = new javax.swing.JLabel();
        txtUcretYatir = new javax.swing.JTextField();
        lblUcretYatir = new javax.swing.JLabel();
        btnYatir = new javax.swing.JButton();
        lblBakiye = new javax.swing.JLabel();
        lblMoneyIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlParaYAtir.setBackground(new java.awt.Color(51, 51, 51));

        lblBakiyeYazi.setForeground(new java.awt.Color(255, 255, 255));

        lblUcretYatir.setFont(new java.awt.Font("OCR A Extended", 1, 12)); // NOI18N
        lblUcretYatir.setForeground(new java.awt.Color(255, 255, 255));
        lblUcretYatir.setText("Yatırmak istediginiz ucreti girin :");

        btnYatir.setBackground(new java.awt.Color(204, 204, 204));
        btnYatir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnYatir.setForeground(new java.awt.Color(0, 0, 0));
        btnYatir.setText("Parayı Yatır");
        btnYatir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYatirActionPerformed(evt);
            }
        });

        lblBakiye.setFont(new java.awt.Font("OCR A Extended", 1, 14)); // NOI18N
        lblBakiye.setForeground(new java.awt.Color(255, 255, 255));
        lblBakiye.setText("Yeni Bakiyeniz :");

        lblMoneyIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bankapp/cash_in_hand_100px.png"))); // NOI18N

        javax.swing.GroupLayout pnlParaYAtirLayout = new javax.swing.GroupLayout(pnlParaYAtir);
        pnlParaYAtir.setLayout(pnlParaYAtirLayout);
        pnlParaYAtirLayout.setHorizontalGroup(
            pnlParaYAtirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlParaYAtirLayout.createSequentialGroup()
                .addGroup(pnlParaYAtirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnYatir, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlParaYAtirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlParaYAtirLayout.createSequentialGroup()
                            .addGap(100, 100, 100)
                            .addComponent(lblMoneyIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlParaYAtirLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(pnlParaYAtirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(pnlParaYAtirLayout.createSequentialGroup()
                                    .addComponent(lblUcretYatir, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtUcretYatir, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlParaYAtirLayout.createSequentialGroup()
                                    .addComponent(lblBakiye, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblBakiyeYazi, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(106, 106, 106))))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        pnlParaYAtirLayout.setVerticalGroup(
            pnlParaYAtirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlParaYAtirLayout.createSequentialGroup()
                .addGroup(pnlParaYAtirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlParaYAtirLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblBakiyeYazi, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlParaYAtirLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lblMoneyIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlParaYAtirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUcretYatir, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUcretYatir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnYatir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(lblBakiye)))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(pnlParaYAtir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(pnlParaYAtir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnYatirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYatirActionPerformed
        // TODO add your handling code here:
       ucret1=txtUcretYatir.getText();
       double bakiye=Double.parseDouble(frm.bakiye1); 
       double ucret=Double.parseDouble(ucret1);
       bakiye=bakiye+ucret;
       frm.bakiye1=Double.toString(bakiye);
       lblBakiyeYazi.setText(frm.bakiye1);
          String fileName="C:\\Users\\ÖZGENUR YILDIZ\\Documents\\NetBeansProjects\\BankApp\\src\\bankapp\\bankaKullanici.txt";
    try {
        FileWriter fWriter = new FileWriter(fileName);
        fWriter.write(frm.bakiye1+"\nOzgenur"+"\n030120042"+"\n0\n0\n0");
        fWriter.close();
           } catch (IOException ex) {
        Logger.getLogger(frmParaCek.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_btnYatirActionPerformed


    public static void main(String args[]) {
   
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmParaYatir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnYatir;
    private javax.swing.JLabel lblBakiye;
    private javax.swing.JLabel lblBakiyeYazi;
    private javax.swing.JLabel lblMoneyIcon;
    private javax.swing.JLabel lblUcretYatir;
    private javax.swing.JPanel pnlParaYAtir;
    private javax.swing.JTextField txtUcretYatir;
    // End of variables declaration//GEN-END:variables
}
